import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { IconButton, Pill } from "@/components/luma-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLuma, usePalette } from "@/lib/luma/context";

type SpaceRow = { key: string; kind: "section"; title: string } | { key: string; kind: "channel"; id: string; name: string; type: "text" | "voice"; unread: number; description?: string };

export default function SpaceScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { spaces } = useLuma();
  const palette = usePalette();
  const space = spaces.find((item) => item.id === id);
  if (!space) return <ScreenContainer className="flex-1"><View style={[styles.screen, { backgroundColor: palette.background, padding: 20 }]}><IconButton icon="arrow-back" label="Go back" onPress={() => router.back()} /><Text style={[styles.overviewTitle, { color: palette.text, marginTop: 28 }]}>Space unavailable</Text><Text style={[styles.overviewCopy, { color: palette.secondary }]}>You may no longer be a member, or its channels are hidden by server permissions.</Text></View></ScreenContainer>;
  const rows: SpaceRow[] = space.groups.flatMap((group) => [{ key: group.id, kind: "section" as const, title: group.title }, ...group.channels.map((channel) => ({ key: channel.id, kind: "channel" as const, ...channel }))]);
  return <ScreenContainer className="flex-1"><View style={[styles.screen, { backgroundColor: palette.background }]}><FlatList data={rows} keyExtractor={(item) => item.key} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.nav}><IconButton icon="arrow-back" label="Go back" onPress={() => router.back()} /><IconButton icon="more-horiz" label="Space options" onPress={() => router.push({ pathname: "/server-admin/[id]", params: { id: space.id } })} /></View><View style={[styles.hero, { backgroundColor: space.accent }]}><View style={styles.monogram}><Text style={styles.monogramText}>{space.initials}</Text></View><Text style={styles.spaceName}>{space.name}</Text><Text style={styles.spaceDescription}>{space.description}</Text><View style={styles.heroMeta}><Pill label={`${space.memberCount} members`} color="rgba(255,255,255,0.16)" /><Pressable onPress={() => router.push("/people")} style={styles.memberButton}><MaterialIcons name="group" size={17} color="#FFFFFF" /><Text style={styles.memberButtonText}>People</Text></Pressable></View></View><View style={styles.overview}><View><Text style={[styles.overviewTitle, { color: palette.text }]}>Your space</Text><Text style={[styles.overviewCopy, { color: palette.secondary }]}>Only channels your signed-in account can view are returned by Supabase.</Text></View><Pressable onPress={() => router.push({ pathname: "/server-admin/[id]", params: { id: space.id } })} style={[styles.settingsLink, { backgroundColor: palette.primarySoft }]}><MaterialIcons name="settings" size={18} color={palette.primary} /></Pressable></View></>} renderItem={({ item }) => { if (item.kind === "section") return <Text style={[styles.section, { color: palette.secondary }]}>{item.title.toUpperCase()}</Text>; return <Pressable onPress={() => router.push({ pathname: "/conversation/[id]", params: { id: item.id } })} accessibilityRole="button" style={({ pressed }) => [styles.channel, { backgroundColor: palette.surface, borderColor: palette.border }, pressed && styles.pressed]}><View style={[styles.channelIcon, { backgroundColor: palette.primarySoft }]}><MaterialIcons name={item.type === "voice" ? "graphic-eq" : "tag"} size={18} color={palette.primary} /></View><View style={styles.channelText}><Text style={[styles.channelName, { color: palette.text }]}>{item.name}</Text><Text numberOfLines={1} style={[styles.channelDetail, { color: palette.secondary }]}>{item.description ?? (item.type === "voice" ? "Voice room" : "Text channel")}</Text></View>{item.unread ? <Pill label={`${item.unread}`} /> : <MaterialIcons name="chevron-right" size={20} color={palette.tertiary} />}</Pressable>; }} /></View></ScreenContainer>;
}

const styles = StyleSheet.create({
  screen: { flex: 1 }, content: { padding: 20, paddingBottom: 100 }, nav: { flexDirection: "row", justifyContent: "space-between", marginBottom: 14 }, hero: { borderRadius: 25, padding: 22 }, monogram: { width: 55, height: 55, borderRadius: 18, backgroundColor: "rgba(255,255,255,0.16)", alignItems: "center", justifyContent: "center" }, monogramText: { color: "#FFFFFF", fontWeight: "800", fontSize: 17 }, spaceName: { color: "#FFFFFF", marginTop: 25, fontSize: 28, lineHeight: 34, letterSpacing: -0.5, fontWeight: "800" }, spaceDescription: { color: "#F5F7FF", fontSize: 14, lineHeight: 20, marginTop: 8 }, heroMeta: { marginTop: 18, flexDirection: "row", alignItems: "center", gap: 9 }, memberButton: { minHeight: 28, paddingHorizontal: 10, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.16)", flexDirection: "row", alignItems: "center", gap: 5 }, memberButtonText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, overview: { marginTop: 19, flexDirection: "row", gap: 15, alignItems: "center" }, overviewTitle: { fontSize: 17, fontWeight: "800" }, overviewCopy: { maxWidth: 282, fontSize: 13, lineHeight: 19, marginTop: 4 }, settingsLink: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" }, section: { letterSpacing: 0.85, fontWeight: "800", fontSize: 11, marginTop: 26, marginBottom: 9 }, channel: { minHeight: 68, borderRadius: 17, padding: 13, borderWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", gap: 11, marginBottom: 9 }, channelIcon: { height: 39, width: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" }, channelText: { flex: 1 }, channelName: { fontSize: 15, fontWeight: "700" }, channelDetail: { fontSize: 12, marginTop: 3 }, pressed: { opacity: 0.7, transform: [{ scale: 0.985 }] },
});
