import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { IconButton, MaterialCard, SectionLabel } from "@/components/luma-ui";
import { ScreenContainer } from "@/components/screen-container";
import { usePalette } from "@/lib/luma/context";

export default function AccountSecurityScreen() {
  const palette = usePalette();
  const [twoFactor, setTwoFactor] = useState(false);
  const [sessions, setSessions] = useState([{ id: "this-device", name: "This Android device", detail: "Active now", current: true }, { id: "browser", name: "Chrome on Windows", detail: "Last active yesterday", current: false }]);
  const toggle2fa = (value: boolean) => { setTwoFactor(value); if (value) Alert.alert("Two-factor setup", "Connect your authentication provider to display a verified TOTP QR code or deliver an email code."); };
  const revoke = (id: string) => { if (id === "this-device") return; setSessions((current) => current.filter((session) => session.id !== id)); };
  return <ScreenContainer className="flex-1"><ScrollView style={[styles.screen, { backgroundColor: palette.background }]} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.head}><IconButton icon="arrow-back" label="Go back" onPress={() => router.back()} /><View><Text style={[styles.title, { color: palette.text }]}>Security</Text><Text style={[styles.subTitle, { color: palette.secondary }]}>Protect your account and manage trusted devices.</Text></View></View><SectionLabel>Two-factor authentication</SectionLabel><MaterialCard><View style={styles.row}><View style={[styles.rowIcon, { backgroundColor: palette.primarySoft }]}><MaterialIcons name="phonelink-lock" size={19} color={palette.primary} /></View><View style={styles.rowText}><Text style={[styles.rowTitle, { color: palette.text }]}>Two-factor authentication</Text><Text style={[styles.rowDetail, { color: palette.secondary }]}>{twoFactor ? "Setup preview enabled" : "Add a second verification step"}</Text></View><Switch value={twoFactor} onValueChange={toggle2fa} trackColor={{ false: palette.border, true: palette.primary }} /></View></MaterialCard><SectionLabel>Active sessions</SectionLabel><MaterialCard>{sessions.map((session, index) => <View key={session.id} style={[styles.session, index < sessions.length - 1 && { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.border }]}><View style={[styles.rowIcon, { backgroundColor: session.current ? palette.primarySoft : palette.surface }]}><MaterialIcons name={session.current ? "smartphone" : "laptop"} size={19} color={session.current ? palette.primary : palette.secondary} /></View><View style={styles.rowText}><Text style={[styles.rowTitle, { color: palette.text }]}>{session.name}</Text><Text style={[styles.rowDetail, { color: palette.secondary }]}>{session.detail}</Text></View>{session.current ? <Text style={[styles.current, { color: palette.success }]}>Current</Text> : <Pressable onPress={() => revoke(session.id)} style={[styles.revoke, { backgroundColor: palette.primarySoft }]}><Text style={[styles.revokeText, { color: palette.primary }]}>Revoke</Text></Pressable>}</View>)}</MaterialCard><View style={[styles.note, { backgroundColor: palette.primarySoft }]}><MaterialIcons name="admin-panel-settings" size={19} color={palette.primary} /><Text style={[styles.noteText, { color: palette.primary }]}>Session records, 2FA factors, and remote revocation must be stored and enforced server-side. The Supabase handoff specifies the required sensitive-function boundary.</Text></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  screen: { flex: 1 }, content: { padding: 20, paddingBottom: 100 }, head: { flexDirection: "row", alignItems: "center", gap: 12 }, title: { fontSize: 24, fontWeight: "800" }, subTitle: { fontSize: 12, marginTop: 2 }, row: { minHeight: 70, padding: 14, flexDirection: "row", alignItems: "center", gap: 11 }, session: { minHeight: 68, padding: 14, flexDirection: "row", alignItems: "center", gap: 11 }, rowIcon: { height: 36, width: 36, borderRadius: 12, alignItems: "center", justifyContent: "center" }, rowText: { flex: 1 }, rowTitle: { fontSize: 15, fontWeight: "800" }, rowDetail: { fontSize: 12, marginTop: 3 }, current: { fontSize: 12, fontWeight: "800" }, revoke: { minHeight: 33, paddingHorizontal: 10, borderRadius: 10, alignItems: "center", justifyContent: "center" }, revokeText: { fontSize: 12, fontWeight: "800" }, note: { marginTop: 20, padding: 14, borderRadius: 16, flexDirection: "row", alignItems: "flex-start", gap: 9 }, noteText: { flex: 1, fontSize: 12, lineHeight: 18, fontWeight: "700" },
});
