import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { IconButton, MaterialCard } from "@/components/luma-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLuma, usePalette } from "@/lib/luma/context";
import { supabase } from "@/lib/luma/supabase";

function LegalRow({ icon, title, detail, onPress }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; detail: string; onPress: () => void }) {
  const palette = usePalette();
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.row, pressed && styles.pressed]} accessibilityRole="button"><View style={[styles.rowIcon, { backgroundColor: palette.primarySoft }]}><MaterialIcons name={icon} size={18} color={palette.primary} /></View><View style={styles.rowText}><Text style={[styles.rowTitle, { color: palette.text }]}>{title}</Text><Text style={[styles.rowDetail, { color: palette.secondary }]}>{detail}</Text></View><MaterialIcons name="chevron-right" size={20} color={palette.tertiary} /></Pressable>;
}

export default function LegalScreen() {
  const palette = usePalette();
  const { session } = useLuma();
  const requestExport = async () => { try { const { error } = await supabase.functions.invoke("request-data-export", { body: {} }); if (error) throw error; Alert.alert("Export requested", "Your request is queued. The completed export status appears in your secure account data when the server job finishes."); } catch (error) { Alert.alert("Could not request export", error instanceof Error ? error.message : "Please try again."); } };
  const requestDeletion = () => Alert.alert("Request account deletion", "Your account is scheduled for deletion in 30 days. You can contact support before that date to cancel if your policy allows.", [{ text: "Cancel", style: "cancel" }, { text: "Request deletion", style: "destructive", onPress: () => void (async () => { try { if (!session?.user.id) throw new Error("Sign in before requesting account deletion."); const { error } = await supabase.from("account_deletion_requests").upsert({ user_id: session.user.id, requested_at: new Date().toISOString(), scheduled_for: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(), cancelled_at: null }); if (error) throw error; Alert.alert("Deletion requested", "The request was saved to your account."); } catch (error) { Alert.alert("Could not request deletion", error instanceof Error ? error.message : "Please try again."); } })() }]);
  return <ScreenContainer className="flex-1"><ScrollView style={[styles.screen, { backgroundColor: palette.background }]} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.head}><IconButton icon="arrow-back" label="Go back" onPress={() => router.back()} /><Text style={[styles.title, { color: palette.text }]}>Trust & policies</Text></View><Text style={[styles.intro, { color: palette.secondary }]}>Discurd stores account, messaging, and community data in Supabase with Row Level Security. These controls write requests to your signed-in account.</Text><Text style={[styles.label, { color: palette.secondary }]}>YOUR RIGHTS</Text><MaterialCard><LegalRow icon="description" title="Terms of service" detail="Community responsibilities and account rules." onPress={() => Alert.alert("Terms of service", "Be respectful, do not misuse the service, and respect applicable law. Accounts may be restricted for severe or repeated violations.")} /><LegalRow icon="policy" title="Privacy policy" detail="What we collect, why, and how to control it." onPress={() => Alert.alert("Privacy policy", "Your deployed policy must identify the controller, lawful bases, retention periods, and deletion process before public launch.")} /><LegalRow icon="download" title="Export my data" detail="Queue a server-side account export." onPress={() => void requestExport()} /><LegalRow icon="delete-outline" title="Delete account" detail="Schedule account deletion after a 30-day notice period." onPress={requestDeletion} /></MaterialCard><Text style={[styles.label, { color: palette.secondary }]}>COMMUNITY SAFETY</Text><MaterialCard><LegalRow icon="gavel" title="Community policy" detail="No harassment, exploitation, spam, or harmful content." onPress={() => Alert.alert("Community policy", "Report harmful content. Moderators review reports, record outcomes, and apply proportionate restrictions under the server policy.")} /><LegalRow icon="security" title="Security & sessions" detail="Two-factor and device controls." onPress={() => router.push("/account-security")} /></MaterialCard><View style={[styles.age, { backgroundColor: palette.primarySoft }]}><MaterialIcons name="cake" size={20} color={palette.primary} /><Text style={[styles.ageText, { color: palette.primary }]}>By entering Discurd, you confirmed that you meet the minimum age requirement applicable to your region.</Text></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  screen: { flex: 1 }, content: { padding: 20, paddingBottom: 100 }, head: { flexDirection: "row", alignItems: "center", gap: 13 }, title: { fontSize: 24, fontWeight: "800" }, intro: { fontSize: 14, lineHeight: 21, marginTop: 20 }, label: { letterSpacing: 0.85, fontSize: 11, fontWeight: "800", marginTop: 26, marginBottom: 9 }, row: { minHeight: 73, padding: 14, flexDirection: "row", alignItems: "center", gap: 11 }, rowIcon: { width: 34, height: 34, borderRadius: 11, alignItems: "center", justifyContent: "center" }, rowText: { flex: 1 }, rowTitle: { fontSize: 15, fontWeight: "800" }, rowDetail: { fontSize: 12, lineHeight: 17, marginTop: 2 }, age: { marginTop: 23, borderRadius: 17, padding: 15, flexDirection: "row", gap: 10, alignItems: "flex-start" }, ageText: { flex: 1, fontSize: 13, lineHeight: 18, fontWeight: "700" }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] },
});
