import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { IconButton, Pill } from "@/components/luma-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLuma, usePalette } from "@/lib/luma/context";

export default function NotificationsScreen() {
  const { notifications } = useLuma();
  const palette = usePalette();
  const open = (targetPath?: string) => { if (targetPath?.startsWith("/")) router.push(targetPath as never); };
  return <ScreenContainer className="flex-1"><View style={[styles.screen, { backgroundColor: palette.background }]}><FlatList data={notifications} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.head}><IconButton icon="arrow-back" label="Go back" onPress={() => router.back()} /><View style={styles.headCopy}><Text style={[styles.title, { color: palette.text }]}>Updates</Text><Text style={[styles.subtitle, { color: palette.secondary }]}>Private notification records from your Supabase account.</Text></View></View>} renderItem={({ item }) => <Pressable onPress={() => open(item.targetPath)} disabled={!item.targetPath} accessibilityRole={item.targetPath ? "button" : undefined} style={({ pressed }) => [styles.notice, { backgroundColor: palette.surface, borderColor: palette.border, opacity: item.readAt ? 0.72 : 1 }, pressed && item.targetPath && styles.pressed]}><View style={[styles.glyph, { backgroundColor: palette.primarySoft }]}><MaterialIcons name={item.kind === "mention" ? "alternate-email" : item.kind === "friend_request" ? "person-add-alt" : item.kind === "call" ? "call" : "notifications-none"} size={20} color={palette.primary} /></View><View style={styles.noticeText}><View style={styles.noticeTop}><Text style={[styles.noticeTitle, { color: palette.text }]}>{item.title}</Text>{item.kind === "mention" ? <Pill label="Mention" /> : null}</View><Text numberOfLines={2} style={[styles.noticeDetail, { color: palette.secondary }]}>{item.body}</Text><Text style={[styles.noticeTime, { color: palette.tertiary }]}>{item.createdAt}</Text></View></Pressable>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="notifications-off" size={30} color={palette.tertiary} /><Text style={[styles.emptyTitle, { color: palette.text }]}>No updates yet</Text><Text style={[styles.emptyText, { color: palette.secondary }]}>New notifications appear here and can be delivered to a registered device when Firebase is configured.</Text></View>} ListFooterComponent={<View style={[styles.push, { backgroundColor: palette.primarySoft }]}><MaterialIcons name="notifications-active" size={19} color={palette.primary} /><Text style={[styles.pushText, { color: palette.primary }]}>Enable device notifications in Settings to register this installed device with the secure token endpoint.</Text></View>} /></View></ScreenContainer>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 20, paddingBottom: 100 }, head: { flexDirection: "row", gap: 12, alignItems: "center", marginBottom: 20 }, headCopy: { flex: 1 }, title: { fontSize: 24, fontWeight: "800" }, subtitle: { fontSize: 12, marginTop: 2 }, notice: { padding: 14, borderWidth: StyleSheet.hairlineWidth, borderRadius: 18, flexDirection: "row", gap: 12, marginBottom: 9 }, glyph: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, noticeText: { flex: 1 }, noticeTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 }, noticeTitle: { flex: 1, fontSize: 15, fontWeight: "800" }, noticeDetail: { fontSize: 13, lineHeight: 18, marginTop: 5 }, noticeTime: { fontSize: 11, marginTop: 6 }, push: { marginTop: 13, borderRadius: 16, padding: 14, flexDirection: "row", gap: 9, alignItems: "center" }, pushText: { flex: 1, fontSize: 12, lineHeight: 17, fontWeight: "700" }, empty: { alignItems: "center", paddingTop: 55, paddingHorizontal: 30 }, emptyTitle: { fontSize: 18, fontWeight: "800", marginTop: 12 }, emptyText: { fontSize: 13, lineHeight: 18, textAlign: "center", marginTop: 5 }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] } });
