import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { IconButton, Pill } from "@/components/luma-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLuma, usePalette } from "@/lib/luma/context";

export default function ReportsScreen() {
  const { reports, resolveReport } = useLuma();
  const palette = usePalette();
  const decide = async (id: string, outcome: "resolved" | "dismissed") => { try { await resolveReport(id, outcome); } catch (error) { Alert.alert("Moderation action failed", error instanceof Error ? error.message : "Your role may not have review permission."); } };
  return <ScreenContainer className="flex-1"><View style={[styles.screen, { backgroundColor: palette.background }]}><FlatList data={reports} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><IconButton icon="arrow-back" label="Go back" onPress={() => router.back()} /><View style={styles.headerText}><Text style={[styles.title, { color: palette.text }]}>Review queue</Text><Text style={[styles.subTitle, { color: palette.secondary }]}>These reports are loaded from Supabase and decisions invoke the authorized moderation function.</Text></View></View>} renderItem={({ item }) => <View style={[styles.report, { backgroundColor: palette.surface, borderColor: palette.border }]}><View style={styles.reportTop}><Pill label={item.status.toUpperCase()} color={item.status === "open" ? palette.primarySoft : "#E6F5F0"} /><Text style={[styles.time, { color: palette.tertiary }]}>{item.createdAt}</Text></View><Text style={[styles.reason, { color: palette.text }]}>{item.reason}</Text><Text style={[styles.meta, { color: palette.secondary }]}>Reporter: {item.reporterId}{item.messageId ? ` · message ${item.messageId}` : ""}</Text>{item.status === "open" ? <View style={styles.actions}><Pressable onPress={() => void decide(item.id, "resolved")} style={[styles.action, { backgroundColor: palette.primary }]}><MaterialIcons name="done" size={16} color="#FFFFFF" /><Text style={styles.actionText}>Resolve</Text></Pressable><Pressable onPress={() => void decide(item.id, "dismissed")} style={[styles.dismiss, { backgroundColor: palette.primarySoft }]}><Text style={[styles.dismissText, { color: palette.primary }]}>Dismiss</Text></Pressable></View> : null}</View>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="verified-user" size={30} color={palette.success} /><Text style={[styles.emptyTitle, { color: palette.text }]}>Nothing needs review.</Text></View>} /></View></ScreenContainer>;
}

const styles = StyleSheet.create({
  screen: { flex: 1 }, content: { padding: 20, paddingBottom: 100 }, header: { flexDirection: "row", gap: 11, alignItems: "center", marginBottom: 20 }, headerText: { flex: 1 }, title: { fontSize: 24, fontWeight: "800" }, subTitle: { fontSize: 12, lineHeight: 17, marginTop: 2 }, report: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 18, padding: 15, marginBottom: 10 }, reportTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, time: { fontSize: 12 }, reason: { fontSize: 16, lineHeight: 22, fontWeight: "700", marginTop: 12 }, meta: { fontSize: 12, marginTop: 6 }, actions: { flexDirection: "row", gap: 8, marginTop: 15 }, action: { minHeight: 37, borderRadius: 12, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 5 }, actionText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" }, dismiss: { minHeight: 37, borderRadius: 12, paddingHorizontal: 12, alignItems: "center", justifyContent: "center" }, dismissText: { fontSize: 13, fontWeight: "800" }, empty: { paddingTop: 72, alignItems: "center" }, emptyTitle: { fontSize: 18, fontWeight: "800", marginTop: 13 },
});
