import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { Avatar, IconButton, screenStyles } from "@/components/luma-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLuma, usePalette } from "@/lib/luma/context";

export default function InboxScreen() {
  const { conversations, currentUser, members } = useLuma();
  const palette = usePalette();
  const s = screenStyles(palette);
  return <ScreenContainer className="flex-1"><View style={s.screen}><FlatList data={conversations} keyExtractor={(item) => item.id} contentContainerStyle={s.content} ListHeaderComponent={<><View style={s.topRow}><View><Text style={s.title}>Messages</Text><Text style={s.subtitle}>Private notes, group threads, and good company.</Text></View><IconButton icon="edit" label="Start a new message" onPress={() => router.push("/new-conversation")} tone="filled" /></View><Pressable onPress={() => router.push("/search")} accessibilityRole="search" style={({ pressed }) => [styles.search, { backgroundColor: palette.surface, borderColor: palette.border }, pressed && styles.pressed]}><MaterialIcons name="search" size={19} color={palette.tertiary} /><Text style={[styles.searchText, { color: palette.secondary }]}>Search messages</Text></Pressable><View style={styles.segmentRow}><Pressable onPress={() => router.push("/people")} style={[styles.segment, { backgroundColor: palette.primarySoft }]}><MaterialIcons name="group" size={16} color={palette.primary} /><Text style={[styles.segmentText, { color: palette.primary }]}>People</Text></Pressable><Pressable onPress={() => router.push("/notifications")} style={[styles.segment, { backgroundColor: palette.surface, borderColor: palette.border }]}><MaterialIcons name="notifications-none" size={16} color={palette.secondary} /><Text style={[styles.segmentText, { color: palette.secondary }]}>Updates</Text></Pressable></View></>} renderItem={({ item }) => { const person = members.find((member) => member.id === item.memberIds.find((id) => id !== currentUser.id)) ?? currentUser; return <Pressable onPress={() => router.push({ pathname: "/conversation/[id]", params: { id: item.id } })} style={({ pressed }) => [styles.row, { backgroundColor: palette.surface, borderColor: palette.border }, pressed && styles.pressed]} accessibilityRole="button"><Avatar initials={item.kind === "group" ? "SC" : person.initials} accent={item.kind === "group" ? "#796BD5" : person.accent} presence={item.kind === "dm" ? person.presence : undefined} /><View style={styles.rowText}><View style={styles.rowTop}><Text style={[styles.name, { color: palette.text }]}>{item.title}</Text>{item.unread ? <Text style={[styles.unreadLabel, { color: palette.primary }]}>{item.unread} new</Text> : null}</View><Text numberOfLines={2} style={[styles.preview, { color: palette.secondary }]}>{item.preview}</Text><Text style={[styles.time, { color: palette.tertiary }]}>{item.updatedAt}</Text></View></Pressable>; }} /></View></ScreenContainer>;
}

const styles = StyleSheet.create({
  search: { height: 46, borderRadius: 15, borderWidth: StyleSheet.hairlineWidth, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 9 }, searchText: { fontSize: 15 }, segmentRow: { flexDirection: "row", gap: 9, marginTop: 13, marginBottom: 12 }, segment: { minHeight: 35, borderRadius: 12, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 6, borderWidth: StyleSheet.hairlineWidth }, segmentText: { fontSize: 13, fontWeight: "700" }, row: { flexDirection: "row", gap: 13, padding: 14, borderWidth: StyleSheet.hairlineWidth, borderRadius: 18, marginTop: 10 }, rowText: { flex: 1 }, rowTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 }, name: { fontSize: 16, fontWeight: "700" }, unreadLabel: { fontSize: 12, fontWeight: "800" }, preview: { fontSize: 14, lineHeight: 19, marginTop: 5 }, time: { fontSize: 12, marginTop: 7 }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] },
});
