import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { Avatar, IconButton, MaterialCard, Pill, SectionLabel, screenStyles } from "@/components/luma-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLuma, usePalette } from "@/lib/luma/context";

export default function HomeScreen() {
  const { conversations, members, currentUser } = useLuma();
  const palette = usePalette();
  const s = screenStyles(palette);
  const recent = conversations.slice(0, 3);
  return <ScreenContainer className="flex-1" containerClassName="bg-background"><View style={s.screen}><FlatList data={recent} keyExtractor={(item) => item.id} contentContainerStyle={s.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<>
    <View style={s.topRow}><View><Text style={s.title}>Good morning, Ava.</Text><Text style={s.subtitle}>You have 4 updates worth seeing.</Text></View><IconButton icon="notifications-none" label="Open notifications" onPress={() => router.push("/notifications")} /></View>
    <MaterialCard style={[styles.focus, { backgroundColor: palette.primary }]}><View><Pill label="FOCUS FOR TODAY" color="rgba(255,255,255,0.16)" /><Text style={styles.focusTitle}>A quieter way to stay close.</Text><Text style={styles.focusCopy}>Your groups have 4 new ideas and one conversation waiting for you.</Text></View><Pressable accessibilityRole="button" onPress={() => router.push("/(tabs)/spaces")} style={({ pressed }) => [styles.focusAction, pressed && styles.pressed]}><Text style={[styles.focusActionText, { color: palette.primary }]}>See spaces</Text><MaterialIcons name="arrow-forward" color={palette.primary} size={18} /></Pressable></MaterialCard>
    <SectionLabel action="View all" onPress={() => router.push("/(tabs)/inbox")}>Recent conversations</SectionLabel>
  </>} renderItem={({ item }) => { const person = members.find((member) => member.id === item.memberIds.find((id) => id !== currentUser.id)) ?? currentUser; return <Pressable onPress={() => router.push({ pathname: "/conversation/[id]", params: { id: item.id } })} accessibilityRole="button" style={({ pressed }) => [styles.conversation, { borderBottomColor: palette.border }, pressed && styles.pressed]}><Avatar initials={item.kind === "group" ? "SC" : person.initials} accent={item.kind === "group" ? "#796BD5" : person.accent} presence={item.kind === "dm" ? person.presence : undefined} /><View style={styles.conversationBody}><View style={styles.conversationTop}><Text style={[styles.conversationName, { color: palette.text }]}>{item.title}</Text><Text style={[styles.time, { color: palette.tertiary }]}>{item.updatedAt}</Text></View><View style={styles.previewRow}><Text numberOfLines={1} style={[styles.preview, { color: palette.secondary }]}>{item.preview}</Text>{item.unread > 0 ? <View style={[styles.unread, { backgroundColor: palette.primary }]}><Text style={styles.unreadText}>{item.unread}</Text></View> : null}</View></View></Pressable>; }} ListFooterComponent={<><SectionLabel>Quick actions</SectionLabel><View style={styles.quickGrid}><Pressable onPress={() => router.push("/people")} style={({ pressed }) => [styles.quick, { backgroundColor: palette.surface, borderColor: palette.border }, pressed && styles.pressed]}><MaterialIcons name="person-add-alt" size={21} color={palette.primary} /><Text style={[styles.quickText, { color: palette.text }]}>Find people</Text></Pressable><Pressable onPress={() => router.push("/search")} style={({ pressed }) => [styles.quick, { backgroundColor: palette.surface, borderColor: palette.border }, pressed && styles.pressed]}><MaterialIcons name="search" size={21} color={palette.primary} /><Text style={[styles.quickText, { color: palette.text }]}>Search</Text></Pressable></View></>} /></View></ScreenContainer>;
}

const styles = StyleSheet.create({
  focus: { padding: 20, borderWidth: 0, gap: 18 }, focusTitle: { color: "#FFFFFF", marginTop: 13, fontWeight: "800", letterSpacing: -0.55, fontSize: 24, lineHeight: 29 }, focusCopy: { color: "#E9EDFF", fontSize: 14, lineHeight: 20, marginTop: 7 }, focusAction: { minHeight: 42, borderRadius: 13, alignSelf: "flex-start", paddingHorizontal: 14, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", gap: 7 }, focusActionText: { fontSize: 14, fontWeight: "800" }, conversation: { flexDirection: "row", paddingVertical: 13, gap: 12, borderBottomWidth: StyleSheet.hairlineWidth }, conversationBody: { flex: 1, justifyContent: "center" }, conversationTop: { flexDirection: "row", justifyContent: "space-between", gap: 12 }, conversationName: { fontSize: 16, fontWeight: "700" }, time: { fontSize: 12, paddingTop: 3 }, previewRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 3 }, preview: { flex: 1, fontSize: 14, lineHeight: 19 }, unread: { width: 20, height: 20, borderRadius: 10, alignItems: "center", justifyContent: "center" }, unreadText: { color: "#FFFFFF", fontSize: 11, fontWeight: "800" }, quickGrid: { flexDirection: "row", gap: 12 }, quick: { flex: 1, borderWidth: StyleSheet.hairlineWidth, borderRadius: 17, padding: 16, minHeight: 106, justifyContent: "space-between" }, quickText: { marginTop: 20, fontSize: 14, fontWeight: "700" }, pressed: { opacity: 0.7, transform: [{ scale: 0.985 }] },
});
