import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { Avatar, MaterialCard, SectionLabel, screenStyles } from "@/components/luma-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLuma, usePalette } from "@/lib/luma/context";

function SettingRow({ icon, label, value, onPress, control }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; label: string; value?: string; onPress?: () => void; control?: React.ReactNode }) {
  const palette = usePalette();
  return <Pressable onPress={onPress} disabled={!onPress} accessibilityRole={onPress ? "button" : undefined} style={({ pressed }) => [styles.settingRow, pressed && onPress && styles.pressed]}><View style={[styles.settingIcon, { backgroundColor: palette.primarySoft }]}><MaterialIcons name={icon} size={18} color={palette.primary} /></View><Text style={[styles.settingLabel, { color: palette.text }]}>{label}</Text>{control ?? <View style={styles.valueBox}>{value ? <Text style={[styles.value, { color: palette.secondary }]}>{value}</Text> : null}{onPress ? <MaterialIcons name="chevron-right" size={20} color={palette.tertiary} /> : null}</View>}</Pressable>;
}

export default function SettingsScreen() {
  const { currentUser, settings, updateSettings, registerPushDevice, signOut } = useLuma();
  const palette = usePalette();
  const s = screenStyles(palette);
  const chooseAppearance = () => Alert.alert("Appearance", "Choose how Discurd should look on this device.", ["system", "light", "dark"].map((appearance) => ({ text: appearance === "system" ? "Match device" : appearance[0].toUpperCase() + appearance.slice(1), onPress: () => void updateSettings({ appearance: appearance as "system" | "light" | "dark" }) })));
  const setNotifications = async (enabled: boolean) => { try { if (enabled) await registerPushDevice(); await updateSettings({ notifications: enabled }); } catch (error) { Alert.alert("Notifications unavailable", error instanceof Error ? error.message : "Build the Android app with Firebase configured, then try again."); } };
  const logout = () => Alert.alert("Sign out", "Your session will be removed from this device.", [{ text: "Cancel", style: "cancel" }, { text: "Sign out", style: "destructive", onPress: () => void signOut() }]);
  return <ScreenContainer className="flex-1"><View style={s.screen}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.topRow}><View><Text style={s.title}>Settings</Text><Text style={s.subtitle}>Your account, safety, and device preferences.</Text></View></View><Pressable onPress={() => router.push({ pathname: "/profile/[id]", params: { id: currentUser.id } })} style={({ pressed }) => [styles.profile, { backgroundColor: palette.surface, borderColor: palette.border }, pressed && styles.pressed]} accessibilityRole="button"><Avatar initials={currentUser.initials} accent={currentUser.accent} size={54} presence={currentUser.presence} /><View style={styles.profileText}><Text style={[styles.profileName, { color: palette.text }]}>{currentUser.name}</Text><Text style={[styles.profileHandle, { color: palette.secondary }]}>@{currentUser.username}</Text></View><MaterialIcons name="chevron-right" size={22} color={palette.tertiary} /></Pressable><SectionLabel>Appearance</SectionLabel><MaterialCard><SettingRow icon="brightness-6" label="Appearance" value={settings.appearance === "system" ? "Match device" : settings.appearance[0].toUpperCase() + settings.appearance.slice(1)} onPress={chooseAppearance} /><SettingRow icon="motion-photos-off" label="Reduce motion" control={<Switch value={settings.reduceMotion} onValueChange={(value) => void updateSettings({ reduceMotion: value })} trackColor={{ false: palette.border, true: palette.primary }} />} /></MaterialCard><SectionLabel>Comfort and alerts</SectionLabel><MaterialCard><SettingRow icon="notifications-none" label="Notifications" control={<Switch value={settings.notifications} onValueChange={(value) => void setNotifications(value)} trackColor={{ false: palette.border, true: palette.primary }} />} /><SettingRow icon="format-line-spacing" label="Compact messages" control={<Switch value={settings.compactMode} onValueChange={(value) => void updateSettings({ compactMode: value })} trackColor={{ false: palette.border, true: palette.primary }} />} /><SettingRow icon="volume-up" label="Voice & video" value="Provider setup required" onPress={() => router.push("/(tabs)/calls")} /></MaterialCard><SectionLabel>Privacy and data</SectionLabel><MaterialCard><SettingRow icon="shield" label="Privacy & safety" onPress={() => router.push("/legal")} /><SettingRow icon="download" label="Export my data" value="Request export" onPress={() => router.push("/legal")} /><SettingRow icon="security" label="Security & sessions" value="2FA & devices" onPress={() => router.push("/account-security")} /></MaterialCard><SectionLabel>Account</SectionLabel><MaterialCard><SettingRow icon="logout" label="Sign out" value="This device" onPress={logout} /></MaterialCard></ScrollView></View></ScreenContainer>;
}

const styles = StyleSheet.create({ profile: { minHeight: 84, borderWidth: StyleSheet.hairlineWidth, padding: 15, borderRadius: 20, flexDirection: "row", alignItems: "center", gap: 13 }, profileText: { flex: 1 }, profileName: { fontSize: 17, fontWeight: "800" }, profileHandle: { fontSize: 14, marginTop: 3 }, settingRow: { minHeight: 58, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", gap: 11 }, settingIcon: { width: 30, height: 30, borderRadius: 10, alignItems: "center", justifyContent: "center" }, settingLabel: { flex: 1, fontSize: 15, fontWeight: "600" }, valueBox: { flexDirection: "row", alignItems: "center", gap: 5 }, value: { fontSize: 13 }, pressed: { opacity: 0.7, transform: [{ scale: 0.985 }] } });
