import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useState } from "react";
import { Avatar, IconButton } from "@/components/luma-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLuma, usePalette } from "@/lib/luma/context";

export default function ThreadScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { messages, members, currentUser, sendMessage } = useLuma();
  const palette = usePalette();
  const [draft, setDraft] = useState("");
  const parent = messages.find((message) => message.id === id);
  const author = members.find((member) => member.id === parent?.authorId) ?? currentUser;
  const replies = messages.filter((message) => message.parentId === id);
  const submit = () => { sendMessage(`thread-${id}`, draft, id); setDraft(""); };
  return <ScreenContainer edges={["top", "left", "right"]} className="flex-1"><KeyboardAvoidingView style={[styles.screen, { backgroundColor: palette.background }]} behavior={Platform.OS === "ios" ? "padding" : undefined}><View style={[styles.header, { backgroundColor: palette.tab, borderBottomColor: palette.border }]}><IconButton icon="arrow-back" label="Go back" onPress={() => router.back()} /><View style={styles.headerCopy}><Text style={[styles.title, { color: palette.text }]}>Thread</Text><Text style={[styles.subtitle, { color: palette.secondary }]}>{replies.length} replies · focused conversation</Text></View></View><FlatList data={replies} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={<View style={[styles.parent, { backgroundColor: palette.surface, borderColor: palette.border }]}><View style={styles.parentTop}><Avatar initials={author.initials} accent={author.accent} size={34} /><View><Text style={[styles.author, { color: palette.text }]}>{author.name}</Text><Text style={[styles.time, { color: palette.tertiary }]}>{parent?.createdAt ?? "Earlier"}</Text></View></View><Text style={[styles.parentBody, { color: palette.text }]}>{parent?.body ?? "This message is no longer available."}</Text></View>} renderItem={({ item }) => { const member = members.find((candidate) => candidate.id === item.authorId) ?? currentUser; return <View style={styles.reply}><Avatar initials={member.initials} accent={member.accent} size={30} /><View style={styles.replyBody}><Text style={[styles.replyName, { color: palette.text }]}>{member.name}</Text><Text style={[styles.replyText, { color: palette.text }]}>{item.body}</Text></View></View>; }} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="forum" size={29} color={palette.primary} /><Text style={[styles.emptyTitle, { color: palette.text }]}>Bring the details here.</Text><Text style={[styles.emptyCopy, { color: palette.secondary }]}>Threads keep a discussion connected without crowding the main timeline.</Text></View>} /><View style={[styles.composer, { backgroundColor: palette.tab, borderTopColor: palette.border }]}><TextInput value={draft} onChangeText={setDraft} placeholder="Reply to thread" placeholderTextColor={palette.tertiary} style={[styles.input, { backgroundColor: palette.surface, borderColor: palette.border, color: palette.text }]} accessibilityLabel="Thread reply" /><Pressable onPress={submit} disabled={!draft.trim()} style={[styles.send, { backgroundColor: draft.trim() ? palette.primary : palette.border }]} accessibilityRole="button"><MaterialIcons name="arrow-upward" size={20} color="#FFFFFF" /></Pressable></View></KeyboardAvoidingView></ScreenContainer>;
}

const styles = StyleSheet.create({
  screen: { flex: 1 }, header: { minHeight: 68, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 11, borderBottomWidth: StyleSheet.hairlineWidth }, headerCopy: { flex: 1 }, title: { fontSize: 17, fontWeight: "800" }, subtitle: { marginTop: 2, fontSize: 12 }, list: { padding: 20, paddingBottom: 14 }, parent: { padding: 15, borderWidth: StyleSheet.hairlineWidth, borderRadius: 18, marginBottom: 15 }, parentTop: { flexDirection: "row", alignItems: "center", gap: 10 }, author: { fontSize: 14, fontWeight: "800" }, time: { fontSize: 11, marginTop: 2 }, parentBody: { fontSize: 15, lineHeight: 22, marginTop: 12 }, reply: { flexDirection: "row", gap: 10, paddingVertical: 10 }, replyBody: { flex: 1 }, replyName: { fontSize: 13, fontWeight: "800" }, replyText: { fontSize: 15, lineHeight: 21, marginTop: 2 }, empty: { alignItems: "center", paddingHorizontal: 26, paddingTop: 35 }, emptyTitle: { fontSize: 18, fontWeight: "800", marginTop: 13 }, emptyCopy: { fontSize: 14, lineHeight: 20, marginTop: 6, textAlign: "center" }, composer: { minHeight: 68, padding: 12, paddingHorizontal: 16, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", gap: 8 }, input: { flex: 1, minHeight: 42, borderWidth: StyleSheet.hairlineWidth, borderRadius: 14, paddingHorizontal: 13, fontSize: 15 }, send: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" },
});
